# Name of workflow
name: Pull Request Action

# When will action run: Trigger workflow on pull request events
# but only for the main branch
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs
jobs:
  # Give job a name
  pull-request:
    #Job only executes if commit message does not contain whatever is in the quotes
    if: ${{ !contains(github.event.head_commit.message, '##') }}

    # define the runner that the job will run on
    runs-on: ubuntu-latest

    # Gives steps: sequence of tasks that will be executed for the job
    steps:
      # check-out your repo under $GITHUB_WORKSPACES, so job can access it
      # Needed because GitHub needs to clone the branch to pipeline
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checking test
        run: echo ${{ github.event.head_commit.message }}

