name: Check pull request and merge if check passes

on:
  pull_request:
    paths: # Run when one or more paths match a pattern listed below
      - artifacts/**
      - src/**
      - notebook/**
      - templates/**
      - logs/**
      - .github/workflows/pull_merge.yaml
    branches:
      - main
  workflow_dispatch:
    
jobs:
  pull-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo # Check out a repo
        uses: actions/checkout@v2

      - name: Setup python version # Set up with a specific version of Python
        uses: actions/setup-python@v2
        with: # inserts input parameters required by an action.
          python-version: 3.8
          cache: pip

      - name: Cache # Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      # - name: Create and start virtual environment
      #   run: |
      #      python -m venv venv
      #      source venv/bin/activate

      - name: Install packages # Install dependencies
        run: pip install -r requirements.txt

      # Next test the changes, the unit testing part.
      # Need to use hypothesis and pandera packages to setup automatic unit testing of app